#!/bin/sh
sudo apt install -y nginx php-fpm php-curl && cp default /etc/nginx/sites-enabled/default && service nginx restart && wget https://github.com/txthinking/brook/releases/download/v20190601/brook
